"""added new relations

Revision ID: 2ac68c9f39cf
Revises: 713c41976e7b
Create Date: 2024-01-24 23:27:01.321944

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '2ac68c9f39cf'
down_revision = '713c41976e7b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('students', schema=None) as batch_op:
        batch_op.alter_column('student_class',
               existing_type=mysql.INTEGER(),
               nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('students', schema=None) as batch_op:
        batch_op.alter_column('student_class',
               existing_type=mysql.INTEGER(),
               nullable=True)

    # ### end Alembic commands ###
