"""added type for assessment

Revision ID: 79cb3b80e2cc
Revises: 2ac68c9f39cf
Create Date: 2024-01-28 00:46:47.968635

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '79cb3b80e2cc'
down_revision = '2ac68c9f39cf'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('assessments', schema=None) as batch_op:
        batch_op.add_column(sa.Column('assessment_type', sa.String(length=100), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('assessments', schema=None) as batch_op:
        batch_op.drop_column('assessment_type')

    # ### end Alembic commands ###
