"""added cascade on delete

Revision ID: b35d50a46821
Revises: 79cb3b80e2cc
Create Date: 2024-01-29 03:20:16.699889

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b35d50a46821'
down_revision = '79cb3b80e2cc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('assessments', schema=None) as batch_op:
        batch_op.drop_constraint('assessments_ibfk_2', type_='foreignkey')
        batch_op.drop_constraint('assessments_ibfk_1', type_='foreignkey')
        batch_op.create_foreign_key(None, 'subjects', ['subject_id'], ['id'], ondelete='CASCADE')
        batch_op.create_foreign_key(None, 'remarks', ['remark_id'], ['id'], ondelete='CASCADE')

    with op.batch_alter_table('grade_assessment', schema=None) as batch_op:
        batch_op.drop_constraint('grade_assessment_ibfk_1', type_='foreignkey')
        batch_op.drop_constraint('grade_assessment_ibfk_3', type_='foreignkey')
        batch_op.drop_constraint('grade_assessment_ibfk_2', type_='foreignkey')
        batch_op.create_foreign_key(None, 'classes', ['class_id'], ['id'], ondelete='CASCADE')
        batch_op.create_foreign_key(None, 'assessments', ['assessment_id'], ['id'], ondelete='CASCADE')
        batch_op.create_foreign_key(None, 'students', ['sid'], ['sid'], ondelete='CASCADE')

    with op.batch_alter_table('grade_remark', schema=None) as batch_op:
        batch_op.drop_constraint('grade_remark_ibfk_1', type_='foreignkey')
        batch_op.drop_constraint('grade_remark_ibfk_2', type_='foreignkey')
        batch_op.drop_constraint('grade_remark_ibfk_3', type_='foreignkey')
        batch_op.create_foreign_key(None, 'students', ['sid'], ['sid'], ondelete='CASCADE')
        batch_op.create_foreign_key(None, 'classes', ['class_id'], ['id'], ondelete='CASCADE')
        batch_op.create_foreign_key(None, 'remarks', ['remark_id'], ['id'], ondelete='CASCADE')

    with op.batch_alter_table('remarks', schema=None) as batch_op:
        batch_op.drop_constraint('remarks_ibfk_1', type_='foreignkey')
        batch_op.create_foreign_key(None, 'subjects', ['subject_id'], ['id'], ondelete='CASCADE')

    with op.batch_alter_table('students', schema=None) as batch_op:
        batch_op.drop_constraint('students_ibfk_1', type_='foreignkey')
        batch_op.create_foreign_key(None, 'classes', ['student_class'], ['id'], ondelete='CASCADE')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('students', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('students_ibfk_1', 'classes', ['student_class'], ['id'])

    with op.batch_alter_table('remarks', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('remarks_ibfk_1', 'subjects', ['subject_id'], ['id'])

    with op.batch_alter_table('grade_remark', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('grade_remark_ibfk_3', 'students', ['sid'], ['sid'])
        batch_op.create_foreign_key('grade_remark_ibfk_2', 'remarks', ['remark_id'], ['id'])
        batch_op.create_foreign_key('grade_remark_ibfk_1', 'classes', ['class_id'], ['id'])

    with op.batch_alter_table('grade_assessment', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('grade_assessment_ibfk_2', 'classes', ['class_id'], ['id'])
        batch_op.create_foreign_key('grade_assessment_ibfk_3', 'students', ['sid'], ['sid'])
        batch_op.create_foreign_key('grade_assessment_ibfk_1', 'assessments', ['assessment_id'], ['id'])

    with op.batch_alter_table('assessments', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('assessments_ibfk_1', 'remarks', ['remark_id'], ['id'])
        batch_op.create_foreign_key('assessments_ibfk_2', 'subjects', ['subject_id'], ['id'])

    # ### end Alembic commands ###
