"""Initial Migrate

Revision ID: d29ed3605243
Revises: 
Create Date: 2024-01-23 01:02:48.508520

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd29ed3605243'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('classes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('subjects',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('remarks',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('subject_id', sa.Integer(), nullable=False),
    sa.Column('content', sa.String(length=100), nullable=False),
    sa.ForeignKeyConstraint(['subject_id'], ['subjects.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('students',
    sa.Column('sid', sa.String(length=100), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('student_class', sa.Integer(), nullable=True),
    sa.Column('dob', sa.DateTime(), nullable=True),
    sa.Column('absentdays', sa.Integer(), nullable=True),
    sa.Column('latedays', sa.Integer(), nullable=True),
    sa.Column('teachercomment', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['student_class'], ['classes.id'], ),
    sa.PrimaryKeyConstraint('sid')
    )
    op.create_table('assessments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('subject_id', sa.Integer(), nullable=False),
    sa.Column('remark_id', sa.Integer(), nullable=False),
    sa.Column('full_mark', sa.Integer(), nullable=False),
    sa.Column('percentage_to_remark', sa.Float(), nullable=False),
    sa.ForeignKeyConstraint(['remark_id'], ['remarks.id'], ),
    sa.ForeignKeyConstraint(['subject_id'], ['subjects.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('grade_remark',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('sid', sa.String(length=100), nullable=False),
    sa.Column('class_id', sa.Integer(), nullable=False),
    sa.Column('remark_id', sa.Integer(), nullable=False),
    sa.Column('grade', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['class_id'], ['classes.id'], ),
    sa.ForeignKeyConstraint(['remark_id'], ['remarks.id'], ),
    sa.ForeignKeyConstraint(['sid'], ['students.sid'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('grade_assessment',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('sid', sa.String(length=100), nullable=False),
    sa.Column('class_id', sa.Integer(), nullable=False),
    sa.Column('assessment_id', sa.Integer(), nullable=False),
    sa.Column('grade', sa.Float(), nullable=True),
    sa.Column('transformedgrade', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['assessment_id'], ['assessments.id'], ),
    sa.ForeignKeyConstraint(['class_id'], ['classes.id'], ),
    sa.ForeignKeyConstraint(['sid'], ['students.sid'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('grade_assessment')
    op.drop_table('grade_remark')
    op.drop_table('assessments')
    op.drop_table('students')
    op.drop_table('remarks')
    op.drop_table('subjects')
    op.drop_table('classes')
    # ### end Alembic commands ###
